# Jekyll build config

paginate: 5

markdown: kramdown
highlighter: rouge
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

title: 'mineworker devlog'
description: '개발 기록과 학습 노트를 쌓는 GitHub 블로그'
author: 'mineworker'
url: 'https://mineworker-x29.github.io'
lang: 'ko-KR'
