disqus:
  comments: false
  disqus_shortname: ''

google-ID: ''

menu:
  - { name: '소개', url: 'about.html' }
  - { name: '글 목록', url: 'writing.html' }
  - { name: '연락처', url: 'contact.html' }

social:
  - { icon: 'github', link: 'https://github.com/mineworker-x29' }
  - { icon: 'envelope', link: 'mailto:hello@example.com' }
  - { icon: 'rss-square', link: '/feed.xml' }

pagination:
  next_page: '다음'
  previous_page: '이전'

sharing_button_prompt: '이 글이 도움이 됐다면 공유해주세요.'
related_posts: '함께 읽으면 좋은 글'
post_date_prefix: '작성일'
